# Copyright (c) 2025, NVIDIA Corporation. All rights reserved.
#
# This work is made available under the NVIDIA One-Way Noncommercial License v1 (NSCLv1).
# To view a copy of this license, please refer to LICENSE

depth: 16
cfg: 1.7
top_k: 1000
top_p: 0.99 
more_smooth: False
mask: True