# Copyright (c) 2025, NVIDIA Corporation. All rights reserved.
#
# This work is made available under the NVIDIA One-Way Noncommercial License v1 (NSCLv1).
# To view a copy of this license, please refer to LICENSE

depth: 24
cfg: 2.1
top_k: 900
top_p: 0.99 
mask: True
more_smooth: False